### PR TITLE
Allow importing module inside Jupyter

### PR DESCRIPTION
**Pull request by philippjfr**
Allows importing module inside Jupyter, e.g. to enable static export with nbconvert.

### CODE REVIEW

**Comment by philippjfr** [comment]
@mattpap Would it be possible for you to merge this and then tag a dev release?

**Comment by mattpap** [comment]
@philippjfr, I will publish later today.

**Comment by philippjfr** [comment]
For reference here's what a static export looks like: https://anaconda.org/philippjfr/ipywidget/notebook

**Comment by mattpap** [comment]
Icons are missing. I'm guessing that the hack that I made to make them work at all, is being overridden by jupyter.

**Comment by philippjfr** [comment]
Yeah, that seems likely, it does display okay in the actual (classic) notebook but disappears in a static export. Can live with it for now.

**Pull request merged**
