### PR TITLE
Embed full state on initial render

### PR DESCRIPTION
**Pull request by philippjfr**
@mattpap Not sure how much you remember about this stuff but basically here I'm including two separate state bundles. The problem that a few libraries I was looking into were not rendering correctly because message containing the state that was sent after the model was rendered was often missing a bunch of properties, e.g. the `_view_name`.

I'd also love to hear your thoughts @peytondmurray and @ndmlny-qs. 

Fixes https://github.com/bokeh/ipywidgets_bokeh/issues/88
Fixes https://github.com/bokeh/ipywidgets_bokeh/issues/89

### CODE REVIEW

**Comment by mattpap** [comment]
I think I don't have anything to contribute here. If it works then I'm fine with merging this. Maybe other reviewers will have better feedback. One thing I would suggest though, is to explain the code in comments and perhaps think how we can test this in the longer term.

**Comment by philippjfr** [comment]
That's a good idea, @ndmlny-qs do you have any time to maybe set up some playwright tests for this repo?

**Comment by philippjfr** [comment]
Only other thing I'd want to check before merging is whether ipywidgets still sends the full state a second time.

**Comment by ndmlny-qs** [comment]
I can confirm that this change works for the anywidget button counter example. These issues are resolved with this change:

- https://github.com/manzt/anywidget/issues/100
- https://github.com/bokeh/ipywidgets_bokeh/issues/89

I do not know about the mapwidget issue https://github.com/bokeh/ipywidgets_bokeh/issues/88, as it requires an account.

@philippjfr can you clarify/give more info around what you mean by `...check before merging is whether ipywidgets still sends the full state a second time.` so I can check it?

**Comment by peytondmurray** [comment]
@philippjfr I really don't have the context to understand this change, but I'm glad that it appears to fix a few of these outstanding issues. Instead I'll just defer to @ndmlny-qs about this.

**Comment by philippjfr** [comment]
This is looking great, thanks @ndmlny-qs!

**Comment by ndmlny-qs** [comment]
The windows tests are failing, and I have no idea how to overcome the issue. I ran the tests on a local windows 10 vm, and got the same failing results. Any clues about how to solve this would be greatly appreciated.

**Comment by ndmlny-qs** [comment]
I had to skip e2e tests for windows in the GH workflow. I thought skipping them in the anywidget module would be sufficient, but pytest will error with a code 5 (https://docs.pytest.org/en/latest/reference/exit-codes.html), i.e. no tests collected. In order to circumvent this error, I had to skip them in the CI

When we have unit tests, this restriction can be removed, and I think we can use the module level pytest.skip() method to skip e2e tests in windows. @mattpap if the tests look good to you, then I'll squash and merge.

**Pull request merged**
